apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      api: external
  template:
    metadata:
      labels:
        app: frontend
        api: external
    spec:
      containers:
      - name: udagram-frontend
        image: trangocquy123/udagram-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
