apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
      api: external
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
      - name: udagram-frontend
        image: trangocquy123/udagram-frontend:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 80
