apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: trangocquy123/reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
